### ISSUE TITLE
Enhancement: tabs

### ISSUE THREAD

**Issue by TAnas0** [FreeTubeApp/FreeTube-Vue#13]
This package [electron-tabs] looks promising.

I barely fiddled around with it and this is what the result could look like:
![image](https://user-images.githubusercontent.com/12121506/74785524-6f144380-52a2-11ea-9db3-3a0000ee64ea.png)

I think this would be very beneficial and provide easier navigation. We might as well open new videos in a tab by default.

Electron is not my forte, so it may take me some time before this could be considered a feature.

If you want to look at my work, [here it is](https://github.com/TAnas0/FreeTube-Vue/tree/tabs-demo)

**Comment by PrestonN** [comment]
I've taken some time to play around with it.  It looks interesting.

This might not be a problem with the tab functionality, but trying to load the index of the app doesn't work.  It behaves this way if you try to open the app outside of Electron.  I haven't spent too much time on figuring out the issue though it's likely that the project has to be ran on a configured server in order to run properly outside of Electron.

I don't know if that will be possible once the app is bundled as a bundled version loads the `index.html` directly versus loading up a localhost server during dev.

If it isn't possible, then something will have to take advantage of `vue-router` to dynamically change the route as tabs are switched without destroying each tab on swap.  If it comes down to it, I can possibly write my own, but I'd rather not if I don't have to.  It would be similar to what [this](https://www.npmjs.com/package/vue-router-spa-tabs) project was trying to achieve, however I couldn't get the project itself to work.

If this package ends up working then I'm more than happy using it moving forward.  Having said that, I likely won't look at it much, so feel free to keep me updated if you continue to work with it.

**Comment by TAnas0** [comment]
I will fiddle more with it, but just so you know, I am a novice at Electron, I can't say much about what you just said :smile: 

Vue is more of my forte for this project, and here are some more interesting packages you can keep aside or take a look at (https://github.com/vuejs/awesome-vue#tabs). I might end up using one of them

**Comment by PrestonN** [comment]
Not a problem!  I'd consider the amount of Electron knowledge needed for this project to be very minimal.

The reasoning is because one of my goals with this rewrite is to make FreeTube more portable and allow for FreeTube to be hosted on a user's server.  This means that in those situations, FreeTube won't have access to any Electron APIs and will need to check to see if Electron is being used or not.  Because of this, I'm actively trying to avoid using Electron APIs unless really needed.  For all intents and purposes, you can view this project as a typical Node / Vue.js project.

The biggest reason that I use Electron is because it allows me to avoid any CORS issues that are typically found when accessing videos from a server.  This means that we can access 1080p+ videos directly and not have to go through any proxy in order to properly play them.

**Comment by TAnas0** [comment]
In the end, we would rather opt for a lightweight VueJS approach, so I am now using [vue-tabs-chrome](https://github.com/viewweiwu/vue-tabs-chrome).

Thing is: each tab should handle its own navigation, which I equate to having its own Vue Router (I may be wrong), created/destroyed when a new tab is created/destroyed.

I wonder how does this affect your recent navigation changes, and if the current router on this repository is the final mature implementation

**Comment by T-vK** [comment]
How about using electrons built-in tab support? Wouldn't that seem like the more obvious way to approach this? 

I really like the idea of having the frontend and backend separated. Maybe we could wrap the frontend in Cordova some day and generate an Android app. And I guess this would also allow for a universal FreeTube webinterface that works in any browser.

**Comment by PrestonN** [comment]
This feature will likely not be included in the initial release.  Because of this, I will close this issue and we can continue the discussion on the main repo once the initial release has passed.
