### ISSUE TITLE
[Feature Request] Sharing settings beetwen apps

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#147]
Hi

I would like to propose to add feature which allow to share settings beetwen apps.
Currently, I think about newpipe and Freetube, but if other similar apps exists, then these apps can be added too.

I think about sharing settings like:

    subscriptions
    movie status (watched, unwatched, current time)

Config file could contain syntax like this
timestamp,id_movie,movie_status,channel

    timestamp - when movie status was saved -> this option could be used to findings which program was used to watch movie (latest watching). For example. If Newpipe will check config file and find in Freetube config file newer timestamp, then Newpipe will use movie_status from Freetube to start watching movie.
    id_movie - url of movie or other id
    movie_status - watched, unwatched, time of movie (hh:mm:ss)

All apps will use own config file, so one app will not overwrite config file second app.
All apps will use specific dir to save config file and next, other synchro app will synchronise these config files.

I will create issues for newpipe and for freetube
NewpPipe: https://github.com/TeamNewPipe/NewPipe/issues/4306

**Comment by PrestonN** [comment]
Some discussion of this has been brought before, so the interest is definitely there.

It's something that I'd like to do at some point, however right now with the current state of FreeTube it isn't going to be a priority for now.  There's still a lot of different features and additions I need to work on before I can consider seriously working on this.

Both teams would first need to come to an agreement on how we'd like to do this.  I'm still in the camp of wanting to sync via WebDAV as that would open up syncing via Nextcloud and other similar solutions.  We'd then have to adjust our internal DBs so that we can be compatible with the other app, or come up with a brand new standard that fits both applications.

There's a member of the community already working on WebDAV support for FreeTube.  If it's something that the NewPipe team would like to be involved in then they are more than welcome to be.

As I mentioned though, it will be a while before I'm ready to look at this and it will be well after the first release.  Since this repo is only for things to be worked on before that release, I will be closing this issue.  You're welcome to create a new issue over on the main repo once the next release has passed.

**Comment by pawlosck** [comment]
Ok, I understand, that currently there are issues with higher priority, but I think, this feature should be implement, so I will recreate this  issue after first release.

Nextcloud support is great, because I am using nextcloud, but not all users use this app, so conffig file should be saved directly in some dir, to other synchro app could synchronise it too.
