### ISSUE TITLE
PiP mode is repeating song from playlist and full player start playing next song

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#155]
1. Open playlist
2. Start playing first song
3. Switch to mini player (Picture in picture mode)
4. wait for end of song

5. Song in PiP is repeated - BUG
6. Full player start playing next song from playlist ->  BUG. Full player shouldn't start, when PiP is active. I didn't do anything. Only switched to PiP.

**Comment by PrestonN** [comment]
I've fixed your first issue, as that was a valid issue and something that should be changed.

For your second issue, I don't think I'd consider that a valid bug.  Forcing the next video to not play wouldn't be respecting your settings if you have enabled "Autoplay Playlists" if the reason it didn't was because PiP was enabled.  In this situation, the video just finished playing, why would be want to not play the next video in this case?  Simply because PiP was enabled?  Nothing is playing anymore so it doesn't really make sense.  The only thing I could imagine would be closing the PiP window before playing the next video, which won't be done for this initial release.

For this reason, I consider this resolved and will be closing the issue.

**Comment by pawlosck** [comment]
For me, more intuitive is situation, when I switch to PiP, then PiP should remember all settings from main player, so, if main player play playlist, PiP should play playlist too.
Main player should be disabled until PiP is active.
It would be great to add more controls to PiP (stop, play, previous, next etc). Yes, I know, It's feature and you will not implement it now.

When you open single movie, then PiP should stop playing at end of movie.
When you open movie and is enabled option "autoplay", then PiP should switch to next movie.
For me, this is intuitive. Other reaction is not make sense.

Ask your friends and maybe they are confirm my opinion.

If you don't agree, then add more options to configure Freetube like KDE. There are a lot of options and all people can configure KDE to own preferences.

PS. Currently I will prevent to report new issues, until you release final version. There are no sense to recreate the same issues later.
