### ISSUE TITLE
Bug : invalid date for upcoming streams

### ISSUE THREAD

**Issue by gamma-zro** [FreeTubeApp/FreeTube-Vue#161]
For upcoming streams the app shows "Premieres on: Invalid Date" message.

**Comment by PrestonN** [comment]
Could you provide an example video?  Premieres are difficult to test with them being more rare unfortunately.

**Comment by gamma-zro** [comment]
Here is the link to the stream : https://www.youtube.com/watch?v=6wbfTcQjePI
Here is the link to the screenshot : https://imgur.com/JnKeK64

**Comment by PrestonN** [comment]
This is sorta fixed.  The problem here is that a date isn't provided in the video you provided.  If I had to guess it's because the premiere date has already passed a couple of days ago.  I've changed the message to state that the video should be starting soon, though I won't be able to have the premiere play the video automatically once that time has passed.  This should at least be a little bit better than showing `invalid date`
