### ISSUE TITLE
Bug : Subscribing to the same channel twice

### ISSUE THREAD

**Issue by gamma-zro** [FreeTubeApp/FreeTube-Vue#162]
Subscribing to the same channel twice. This might be happening because I used two different channel URLs.

* https://www.youtube.com/user/jointhebibleproject
* https://www.youtube.com/channel/UCVfwlh9XpX2Y_tQfjeln9QA

They both point to the same channel but has different URLs

**Comment by PrestonN** [comment]
Could you please add instructions on reproducing the ability to subscribe to a channel multiple times?  I'm having trouble doing so even with the links you provided.

**Comment by ThatIsAPseudo** [comment]
I had the same issue doing the following :
1) Follow channels within Freetube
2) Import subscriptions from OPML file, some of which you already followed at step 1
3) These channels may appear twice

**Comment by gamma-zro** [comment]
It happened after I imported the Freetubedb from the Freetube app

**Comment by PrestonN** [comment]
I've gone ahead and made the fix for OPML and NewPipe imports.  I'm probably not going to be creating the fix for old FreeTube imports as I'm hoping to remove that functionality in a future update, so the time can probably be used elsewhere.  I may come back to it if it's serious but for now unsubscribing and resubscribing to the effected channel(s) can fix it.
