### ISSUE TITLE
Comment scraper not work (i have test on kubuntu AppImage file)

### ISSUE THREAD

**Issue by dasaferi** [FreeTubeApp/FreeTube-Vue#169]
I have test some last pushed changes release build from actions and comment scraper not work have infinite loading.
sorry if I didn't have to open an issue regarding this thing, congratulations you are doing a good job unfortunately I don't know vue.js
![Screenshot_20200927_230153](https://user-images.githubusercontent.com/71762370/94375740-249b5500-0116-11eb-86d4-8253c7e688b2.png)

**Comment by PrestonN** [comment]
I believe the problem with this is because right now the module that grabs comments is being grabbed through my own Repository instead of being officially published like most modules are.  Something about this isn't liked by the builder.  Once my changes are pushed upstream (around Tuesday) then this should be fixed.

**Comment by PrestonN** [comment]
This should be fixed now.

**Comment by dasaferi** [comment]
Thanks
