### ISSUE TITLE
Enhancement: Youtube Easter eggs

### ISSUE THREAD

**Issue by Atrate** [FreeTubeApp/FreeTube-Vue#40]
### This is literally priority 0, just something I thought of due to the new, more YT-like design.

In the distant future when FreeTube is the leading way of watching Youtube content and everyoene on Earth strives to eradicate all semblance of proprietary software from their lives, it might be nice if FreeTube supported some of YouTube's easter eggs — such as typing `"amazing"` while in the player making the progressbar flash rainbow.

**Comment by PrestonN** [comment]
As you mentioned, this would end up being the lowest of priority compared to everything else that needs to be done.  If new features are really light as far as requests and needs go, I can look at doing more fun things like this, but I wouldn't expect to see anything like this in the foreseeable future.

I'll go ahead and close this for now, because by the time I get to this, everything will be moved back to the main repo and it will definitely not be worked on while trying to get the rewrite up to parity with the live release.  Feel free to ask for an update once the rewrite is finished though.
