### ISSUE TITLE
Enhancement: Skip silences

### ISSUE THREAD

**Issue by T-vK** [FreeTubeApp/FreeTube-Vue#41]
NewPipe has a feature that allows you to automatically skip silences in videos allowing you to watch many videos, especially podcasts, way more efficiently without increasing the playback speed.
I would love to see such a feature in FreeTube.

NewPipe utilizes [ExoPlayer](https://github.com/google/ExoPlayer) to do this btw.

**Comment by PrestonN** [comment]
ExoPlayer seems to be Android only.  At this point I don't think I'm too keen to swap to another player for what would be a fourth time in this project's lifespan.

I'm more than happy to implement this if there's a reliable way to detect silence within a video.  I did a quick search and couldn't find anything that supported video.js.  If you're able to find something that might help please let me know and I can implement it.

**Comment by T-vK** [comment]
Related:
[How to generate HTML5 video volume level chart?](https://stackoverflow.com/questions/48031793/how-to-generate-html5-video-volume-level-chart)
[https://stackoverflow.com/questions/20769261/how-to-get-video-elements-current-level-of-loudness](How to get video element's current level of loudness)

I've modified [this](http://jsfiddle.net/v9j7z/106/) fiddle to show an indicator whenever silences are detected:
http://jsfiddle.net/wjd2pq8y/3/

Probably needs some fine tuning.

So if video.js allows accessing lower level objects like the AutioContext instance, this should work.

**Comment by PrestonN** [comment]
The one thing I completely forgot to comment on about this, is that while it's great that we have an example for detecting silence within a video, the issue is that we don't know how long this silence lasts and where the stopping point would be.  This information would need to be known before the user gets to that part within the video.  That makes this current solution very difficult to use.

Either way, this isn't something I'll be focusing on for the initial release.  Please feel free to create a new issue under the main repo to continue this discussion if you'd like once the initial release has passed..

**Comment by T-vK** [comment]
I think ExoPlayer does it in real-time and is not actually skipping the silences, but enabling fast-forward during silences.
