### ISSUE TITLE
New NPM Package: Trending Scraper

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#60]
Out of all of the functionality within FreeTube, the one part of the Invidious API that does not have a local API equivalent is functionality for the Trending page.  Ideally, a new NPM package should be created that is dedicated to this logic.  I will likely do this myself at some point but if someone wants to create this then I see no reason for them to do so.  If you plan on creating this then please let me know.  The current list of videos from the Trending page in FreeTube can be used as a reference for what needs to be included in the package.  Feel free to let me know if there are any questions.

**Comment by GilgusMaximus** [comment]
Okay with adjusting some parts [YT-Channel-Info](https://github.com/FreeTubeApp/yt-channel-info) I got all the data that is requires to build a npm module.

As suggested in the matrix chat, the output should be similar to the Invidious API output in JSON form (as seen [here](https://invidio.us/api/v1/trending)) I would probably drop the value 'descriptionHtml' as it is the same as 'description' but leave everything else in as these things can be used later on in the development of the program. 

One question remaining is the display of horizontal video arrangements (see below). If there is an incentive to display the trending page in a similar fashion to YouTube, these videos can be used. Otherwise I would advise against their usage (at least against the usage of all videos) because then 6 videos of the same creator will be displayed in a row.

![image](https://user-images.githubusercontent.com/34301369/89461981-08f67c80-d76d-11ea-9088-204e4123cbfb.png)

**Comment by PrestonN** [comment]
I agree with you that `descriptionHtml` isn't needed.

As for the horizontal videos, we can probably ignore those as well.  As you mentioned, it wouldn't make sense to have a Trending section with several videos all from the same channel.  Feel free to move forward with not including these.

**Comment by GilgusMaximus** [comment]
Okay I finished the package. It can be viewed on it's [repository](https://github.com/GilgusMaximus/yt-trending-scraper) and installed via [npm](https://www.npmjs.com/package/yt-trending-scraper):
`npm i yt-trending-scraper`.

**Comment by PrestonN** [comment]
Going to go ahead and close this as the trending scraper has been created and fully implemented into FreeTube
