### ISSUE TITLE
Storyboards Cannot be Grabbed

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#64]
Currently, FreeTube is able to successfully return a Storyboard URL as you can see from [this](https://github.com/FreeTubeApp/FreeTube-Vue/blob/master/src/renderer/views/Watch/Watch.js#L290) code.  When attempting to grab from this URL, YouTube returns a 403, regardless if it's within FreeTube or through a browser.  Invidious is able to get storyboards without a problem so there should be some method to allow these to be grabbed properly.  If anyone has any insight then I'd greatly appreciate it.

**Comment by omarroth** [comment]
It's returning 403 because it's a template, not a directly usable URL. The Invidious implementation is [here](https://github.com/iv-org/invidious/blob/452d1e8/src/invidious/videos.cr#L623-L690) and [here](https://github.com/iv-org/invidious/blob/452d1e8/src/invidious.cr#L3702-L3780).

In Javascript it would look something like:

```javascript
let templateUrl = 'https://i9.ytimg.com/sb/H8Gd9t7FQqI/storyboard3_L$L/$N.jpg?sqp=-oaymwGBQ7gymY2Drpcg|80#45#158#10#10#10000#M$M#rs$AOn4CLBmFesZLLYKWd0UNT36Xx79Glm1zQ|160#90#158#5#5#10000#M$M#rs$AOn4CLAMIjIKYqm6PxJnW7fSiydSpGJl5A';
let storyboards = templateUrl.split('|');

let baseUrl = storyboards.shift();
storyboards.forEach((storyboard, i) => {
    let [width, height, count, sWidth, sHeight, interval, _, sigh] = storyboard.split('#');
    let baseStoryboardUrl = baseUrl.sub('$L', i).sub('$N', 'M$M');

    // ...
});

```

Each sprite contains `sWidth*sHeight` thumbnails, each with an individual resolution of `width*height`. A new thumbnail is taken every `interval` milliseconds. There's some more details on how to form a sprite URL in the code I linked. Let me know if anything isn't clear. [This](https://support.jwplayer.com/articles/how-to-add-preview-thumbnails) article may also be helpful on how sprites  are used.

**Comment by GilgusMaximus** [comment]
So just to understand that correctly, the template URL is split according to the code over in Invidious and then the final URL for the first image of your example template would be:

`https://i9.ytimg.com/sb/H8Gd9t7FQqI/storyboard3_L0/M$M.jpg?sqp=-oaymwGBQ7gymY2Drpcg&sigh=rs$AOn4CLBmFesZLLYKWd0UNT36Xx79Glm1zQ`

**Comment by PrestonN** [comment]
Storyboards have been added as of #78 which means we can go ahead and close this issue.
