### ISSUE TITLE
How private is the local API option in FreeTube-Vue?

### ISSUE THREAD

**Issue by randyrandersn** [FreeTubeApp/FreeTube-Vue#68]
With invidious main developer burning out & walking away, and most invidious instances barely usable as a Freetube backend currently, I gave the Freetube-Vue dev build a go using the local api backend option.

So far so good, was working much better.  Will be a proper replacement once subscriptions are finished.  All test video links played perfectly too.  Impressive.

How does the local api backend work (cliff notes are fine) and are there any privacy implications using it as compared with a backend like invidious?  Anything other than IP address for google to identify and track with?

How does it handle the onerous google captcha system?  Are there any local cookies or anything of the sort used or persisted between FT-V sessions?

Thanks for this tool and keep up the good work.

**Comment by PrestonN** [comment]
I'll copy / paste a response I left over on Reddit.

> The downsides / upsides of the local API would be extremely similar to the pros / cons of NewPipe.

> For pros, there is no server outside of YouTube that you are connecting to, which means that there are no concerns for server costs and bandwidth, something that has been very costly for Invidious so far. It also means you're much less likely to be blocked by YouTube since your traffic to the site is much smaller.

> For cons, there is no server outside of YouTube that you are connecting to, which means that there are fewer options for proxying your traffic to YouTube. It also means that whenever there are issues with the API, the user will have to update their app to fix them where else only the instance itself had to be updated.

> There might be a few smaller differences between the two, but these were the major ones. They both have different trade offs so it's very dependent on your values.

As for solving captcha, I'm hoping that it won't be as big of an issue since the requests are tied to your machine instead of one central server.  It'll be much much harder to be rate limited by YouTube when it's just yourself.  It isn't very easy to test either.  As a user, assuming you're using a VPN, switching the VPN you're using can be a quick and easy way to bypass this limit if / when it occurs for you.

As for cookies, nothing should be stored.  We're making requests to YouTube in the background like NewPipe does but it's done in a way where cookies shouldn't be saved on the users machine.  This is already being done in the live release and I plan on doing this in the rewrite, but I will be setting it up so that your cache / cookies will be deleted when closed as a safety measure.

If you do happen to notice anything odd being saved please let me know and I will do my best to resolve that.

If I have answered all of your questions, please close this issue.

**Comment by randyrandersn** [comment]
Thanks for the info.

Now you mention newpipe and the similarities, my question was similar to this one.

https://www.reddit.com/r/NewPipe/comments/i440zs/securityprivacy_questions_about_newpipe/

My concerns center more around fingerprinting a local device through scripts run within an electron app.  Without spoofing fingerprints are a pretty accurate way of identifying and thus tracking a user.  Not providig this info and thus "standing out" as abnormal traffic is not a huge concern to me, as long as no detailed fingerprint details is exposed through FT-Vue, and the requests remain mostly anonymous.

Just to clarify there are cookies kept per session that will be cleaned out upon FT-Vue exit?

Thanks.

**Comment by PrestonN** [comment]
The only scripts that are ran within the app are the scripts specific to FreeTube.  No scripts from YouTube itself are ran.  FreeTube only makes a request to YouTube and parses the data needed from those requests.  YouTube doesn't know what is done with the data once it is sent.

Some cookies are saved per session, though I haven't been able to find anything that can be used to track your habits.  As mentioned, this will be cleared out every session.  I can possibly add a UI element to manually do this as well if it's wanted.

Finally, a VPN can help a ton to prevent any tracking done based on your IP address.  In addition to this, the ability to connect to Tor via a Socks5 proxy will be available in the future as well, further enhancing your privacy.

**Comment by PrestonN** [comment]
I believe I have answered all of your questions, so I will be closing this issue now.

Feel free to ping me if you ever have any more questions.
