### ISSUE TITLE
Localization inconsistency

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube-Vue#80]
The localization does work most of the time, however there are two major spots where it does not provide complete accuracy.

On the one hand, the string for the time since upload does not display the translation into other languages. Neither on the trending / most popular pages, nor on the search pages. A fix could be the creation of template strings in each translation, where the data is put in.

![Upload time](https://user-images.githubusercontent.com/34301369/90412710-bb9fd680-e0ad-11ea-9411-dfc90c6df8f2.png)

Additionally, the string for 'views' as well as other strings are specifically coded to be lower case, which leads to an incorrect display of a translation string, where YouTube usually displays upper case, e.g. "Aufrufe" in german instead of "aufrufe" (in english views).

These lower case function calls are mostly done in .vue files like ft-list-video.vue. However to avoid inconsistencies in other languages, it is probably required to remove that completely and create both an upper case and lower case string of the words that appear in both ways in the program.

![View string](https://user-images.githubusercontent.com/34301369/90413009-30731080-e0ae-11ea-807e-0e7f2a1a1942.png)

**Comment by PrestonN** [comment]
The first issue you mentioned is because the backend is currently returning hard coded strings for the published date.  Some small logic will need to be made that can determine what the translation will be.

The second issue is potentially more complicated.  I'd like to avoid having logic specific to changing strings depending on the active localization.  Either creating new strings in the yaml file that are specific to lower case versions or simply removing the lower case logic all together is fine with me.  All pages you mentioned use the same component so making the fix in one spot will fix it in all locations.

I'm open to suggestions for this.

**Comment by PrestonN** [comment]
This issue has been fixed and so I will be closing this issue.
